Search.appendIndex(
    [
                {
            "fqsen": "\\chillerlan\\SimpleCache\\APCUCache",
            "name": "APCUCache",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-APCUCache.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\APCUCache\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-APCUCache.html#method_get"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\APCUCache\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-APCUCache.html#method_set"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\APCUCache\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-APCUCache.html#method_delete"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\APCUCache\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-APCUCache.html#method_clear"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract",
            "name": "CacheDriverAbstract",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "CacheDriverAbstract\u0020constructor.",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_has"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003AgetMultiple\u0028\u0029",
            "name": "getMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_getMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003AsetMultiple\u0028\u0029",
            "name": "setMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_setMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003AdeleteMultiple\u0028\u0029",
            "name": "deleteMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_deleteMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003AcheckKey\u0028\u0029",
            "name": "checkKey",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_checkKey"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003AcheckKeyArray\u0028\u0029",
            "name": "checkKeyArray",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_checkKeyArray"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_getData"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003AgetTTL\u0028\u0029",
            "name": "getTTL",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_getTTL"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003AcheckReturn\u0028\u0029",
            "name": "checkReturn",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#method_checkReturn"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheDriverAbstract\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheDriverAbstract.html#property_options"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheException",
            "name": "CacheException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheException.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheOptions",
            "name": "CacheOptions",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheOptions.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheOptionsTrait",
            "name": "CacheOptionsTrait",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheOptionsTrait.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheOptionsTrait\u003A\u003A\u0024cacheFilestorage",
            "name": "cacheFilestorage",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheOptionsTrait.html#property_cacheFilestorage"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\CacheOptionsTrait\u003A\u003A\u0024cacheSessionkey",
            "name": "cacheSessionkey",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-CacheOptionsTrait.html#property_cacheSessionkey"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\FileCache",
            "name": "FileCache",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-FileCache.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\FileCache\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "FileCache\u0020constructor.",
            "url": "classes/chillerlan-SimpleCache-FileCache.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\FileCache\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-FileCache.html#method_get"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\FileCache\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-FileCache.html#method_set"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\FileCache\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-FileCache.html#method_delete"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\FileCache\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-FileCache.html#method_clear"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\FileCache\u003A\u003AgetFilepath\u0028\u0029",
            "name": "getFilepath",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-FileCache.html#method_getFilepath"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\FileCache\u003A\u003A\u0024cachedir",
            "name": "cachedir",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-FileCache.html#property_cachedir"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-InvalidArgumentException.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache",
            "name": "MemcachedCache",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MemcachedCache\u0020constructor.",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#method_get"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#method_set"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#method_delete"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#method_clear"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003AgetMultiple\u0028\u0029",
            "name": "getMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#method_getMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003AsetMultiple\u0028\u0029",
            "name": "setMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#method_setMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003AdeleteMultiple\u0028\u0029",
            "name": "deleteMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#method_deleteMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemcachedCache\u003A\u003A\u0024memcached",
            "name": "memcached",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemcachedCache.html#property_memcached"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemoryCache",
            "name": "MemoryCache",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemoryCache.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemoryCache\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemoryCache.html#method_get"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemoryCache\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemoryCache.html#method_set"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemoryCache\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemoryCache.html#method_delete"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemoryCache\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemoryCache.html#method_clear"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\MemoryCache\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-MemoryCache.html#property_cache"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache",
            "name": "RedisCache",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "RedisCache\u0020constructor.",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#method_get"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#method_set"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#method_delete"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#method_clear"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003AgetMultiple\u0028\u0029",
            "name": "getMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#method_getMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003AsetMultiple\u0028\u0029",
            "name": "setMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#method_setMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003AdeleteMultiple\u0028\u0029",
            "name": "deleteMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#method_deleteMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\RedisCache\u003A\u003A\u0024redis",
            "name": "redis",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-RedisCache.html#property_redis"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\SessionCache",
            "name": "SessionCache",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-SessionCache.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\SessionCache\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "SessionCache\u0020constructor.",
            "url": "classes/chillerlan-SimpleCache-SessionCache.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\SessionCache\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-SessionCache.html#method_get"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\SessionCache\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-SessionCache.html#method_set"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\SessionCache\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-SessionCache.html#method_delete"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\SessionCache\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-SessionCache.html#method_clear"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache\\SessionCache\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/chillerlan-SimpleCache-SessionCache.html#property_key"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\APCUTest",
            "name": "APCUTest",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-APCUTest.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\APCUTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-APCUTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\APCUTest\u003A\u003AtestSetTTL\u0028\u0029",
            "name": "testSetTTL",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-APCUTest.html#method_testSetTTL"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\APCUTest\u003A\u003AtestSetMultipleTTL\u0028\u0029",
            "name": "testSetMultipleTTL",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-APCUTest.html#method_testSetMultipleTTL"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\FileCacheTest",
            "name": "FileCacheTest",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-FileCacheTest.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\FileCacheTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-FileCacheTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\FileCacheTest\u003A\u003AtestFileCacheInvalidDirException\u0028\u0029",
            "name": "testFileCacheInvalidDirException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-FileCacheTest.html#method_testFileCacheInvalidDirException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\FileCacheTest\u003A\u003AtestFileCacheDirnotWritableException\u0028\u0029",
            "name": "testFileCacheDirnotWritableException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-FileCacheTest.html#method_testFileCacheDirnotWritableException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\FileCacheTest\u003A\u003AtestClearIgnoresParentDirectory\u0028\u0029",
            "name": "testClearIgnoresParentDirectory",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-FileCacheTest.html#method_testClearIgnoresParentDirectory"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\FileCacheTest\u003A\u003ACACHEDIR",
            "name": "CACHEDIR",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-FileCacheTest.html#constant_CACHEDIR"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\FileCacheTest\u003A\u003AREADONLY",
            "name": "READONLY",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-FileCacheTest.html#constant_READONLY"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\MemcachedTest",
            "name": "MemcachedTest",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-MemcachedTest.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\MemcachedTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-MemcachedTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\MemcachedTest\u003A\u003AtestMemcachedDriverNoServerException\u0028\u0029",
            "name": "testMemcachedDriverNoServerException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-MemcachedTest.html#method_testMemcachedDriverNoServerException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\MemoryCacheTest",
            "name": "MemoryCacheTest",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-MemoryCacheTest.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\MemoryCacheTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-MemoryCacheTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\NonpersistentTestAbstract",
            "name": "NonpersistentTestAbstract",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-NonpersistentTestAbstract.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\NonpersistentTestAbstract\u003A\u003AtestGet\u0028\u0029",
            "name": "testGet",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-NonpersistentTestAbstract.html#method_testGet"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\NonpersistentTestAbstract\u003A\u003AtestDelete\u0028\u0029",
            "name": "testDelete",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-NonpersistentTestAbstract.html#method_testDelete"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\NonpersistentTestAbstract\u003A\u003AtestHas\u0028\u0029",
            "name": "testHas",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-NonpersistentTestAbstract.html#method_testHas"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\NonpersistentTestAbstract\u003A\u003AtestGetMultiple\u0028\u0029",
            "name": "testGetMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-NonpersistentTestAbstract.html#method_testGetMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\NonpersistentTestAbstract\u003A\u003AtestDeleteMultiple\u0028\u0029",
            "name": "testDeleteMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-NonpersistentTestAbstract.html#method_testDeleteMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\NonpersistentTestAbstract\u003A\u003AtestClear\u0028\u0029",
            "name": "testClear",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-NonpersistentTestAbstract.html#method_testClear"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\RedisTest",
            "name": "RedisTest",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-RedisTest.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\RedisTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-RedisTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SessionDriverTest",
            "name": "SessionDriverTest",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SessionDriverTest.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SessionDriverTest\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SessionDriverTest.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SessionDriverTest\u003A\u003AtestEmptyKeyException\u0028\u0029",
            "name": "testEmptyKeyException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SessionDriverTest.html#method_testEmptyKeyException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract",
            "name": "SimpleCacheTestAbstract",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_setUp"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestInstance\u0028\u0029",
            "name": "testInstance",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testInstance"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSet\u0028\u0029",
            "name": "testSet",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSet"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSetTTL\u0028\u0029",
            "name": "testSetTTL",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSetTTL"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSetInvalidTTLException\u0028\u0029",
            "name": "testSetInvalidTTLException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSetInvalidTTLException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSetInvalidKeyException\u0028\u0029",
            "name": "testSetInvalidKeyException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSetInvalidKeyException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestGet\u0028\u0029",
            "name": "testGet",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testGet"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestGetInvalidKeyException\u0028\u0029",
            "name": "testGetInvalidKeyException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testGetInvalidKeyException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestHas\u0028\u0029",
            "name": "testHas",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testHas"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestHasInvalidKeyException\u0028\u0029",
            "name": "testHasInvalidKeyException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testHasInvalidKeyException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestDelete\u0028\u0029",
            "name": "testDelete",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testDelete"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestDeleteInvalidKeyException\u0028\u0029",
            "name": "testDeleteInvalidKeyException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testDeleteInvalidKeyException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSetMultiple\u0028\u0029",
            "name": "testSetMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSetMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSetMultipleTTL\u0028\u0029",
            "name": "testSetMultipleTTL",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSetMultipleTTL"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSetMultipleInvalidTTLException\u0028\u0029",
            "name": "testSetMultipleInvalidTTLException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSetMultipleInvalidTTLException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSetMultipleInvalidDataException\u0028\u0029",
            "name": "testSetMultipleInvalidDataException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSetMultipleInvalidDataException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestSetMultipleInvalidKeyException\u0028\u0029",
            "name": "testSetMultipleInvalidKeyException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testSetMultipleInvalidKeyException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestGetMultiple\u0028\u0029",
            "name": "testGetMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testGetMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestGetMultipleInvalidDataException\u0028\u0029",
            "name": "testGetMultipleInvalidDataException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testGetMultipleInvalidDataException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestGetMultipleInvalidKeyException\u0028\u0029",
            "name": "testGetMultipleInvalidKeyException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testGetMultipleInvalidKeyException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestDeleteMultiple\u0028\u0029",
            "name": "testDeleteMultiple",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testDeleteMultiple"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestDeleteMultipleInvalidDataException\u0028\u0029",
            "name": "testDeleteMultipleInvalidDataException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testDeleteMultipleInvalidDataException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestDeleteMultipleInvalidKeyException\u0028\u0029",
            "name": "testDeleteMultipleInvalidKeyException",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testDeleteMultipleInvalidKeyException"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003AtestClear\u0028\u0029",
            "name": "testClear",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#method_testClear"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#property_cache"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest\\SimpleCacheTestAbstract\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/chillerlan-SimpleCacheTest-SimpleCacheTestAbstract.html#property_options"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCache",
            "name": "SimpleCache",
            "summary": "",
            "url": "namespaces/chillerlan-simplecache.html"
        },                {
            "fqsen": "\\chillerlan",
            "name": "chillerlan",
            "summary": "",
            "url": "namespaces/chillerlan.html"
        },                {
            "fqsen": "\\chillerlan\\SimpleCacheTest",
            "name": "SimpleCacheTest",
            "summary": "",
            "url": "namespaces/chillerlan-simplecachetest.html"
        }            ]
);
