build:
  tests:
   override:
    -
      command: 'vendor/bin/phpunit --coverage-clover=coverage'
      coverage:
        file: 'coverage'
        format: 'clover'
filter:
  excluded_paths:
    - tests/*
