language: php

matrix:
  include:
  - php: 7.2
  - php: 7.3
  - php: nightly
  allow_failures:
  - php: nightly

services:
  - memcached
  - redis-server
  - apcu

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_success: bash <(curl -s https://codecov.io/bash)
