language: php

php:
  - 7.0
  - 7.1

services:
  - memcached
  - redis-server

before_install: pip install --user codecov
install: travis_retry composer install --no-interaction --prefer-source
before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml
after_success: codecov
