language: php

php:
  - 7.0
  - 7.1

services:
  - memcached
  - redis-server

before_install: pip install --user codecov
install: travis_retry composer install --no-interaction --prefer-source
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml
after_success: codecov
