language: php

php:
  - 7.0
  - 7.1

before_install: pip install --user codecov
install: travis_retry composer install --no-interaction --prefer-source
before_script:
  - git clone https://github.com/php-memcached-dev/php-memcached
  - cd php-memcached && git checkout php7 && git pull
  - /usr/local/php7/bin/phpize
  - ./configure --with-php-config=/usr/local/php7/bin/php-config
  - make && sudo make install
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml
after_success: codecov
