language: php

services:
  - memcached
  - redis-server
  - apcu

env:
  global:
    - PHAN_ALLOW_XDEBUG=0 PHAN_DISABLE_XDEBUG_WARN=1

matrix:
  include:
    - php: 7.4
    - php: 8.0
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - pecl channel-update pecl.php.net
  - pecl install ast

install:
  - composer install --no-interaction --prefer-source
  - composer validate

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpunit --configuration phpunit.xml
  - vendor/bin/phan

after_success: bash <(curl -s https://codecov.io/bash)
